-- Scoop Dogg - seed every setting.
--
-- GENERATED by scripts/build-settings-migration.mjs from content/settings.seed.json.
-- Do not hand-edit; regenerate. After seeding, the DATABASE is the source of truth and
-- Josue edits these in the admin - this file is only the starting position.
--
-- Every default is sourced, most from promises his own site already makes, so if he
-- never opens the settings screen the business runs on what he has publicly committed to.

begin;

-- site
insert into settings (key, value, updated_by) values ('business.name', '"Scoop Dogg"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- current notify-new-lead function
insert into settings (key, value, updated_by) values ('business.timezone', '"America/Los_Angeles"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- site
insert into settings (key, value, updated_by) values ('business.phone', '"(805) 869-8070"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- site
insert into settings (key, value, updated_by) values ('business.email', '"josue@scoopdogg.net"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- factual; covers 13 of 16 cities
insert into settings (key, value, updated_by) values ('business.region_label', '"Ventura County and nearby"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- researched 2026-09-10. Headline copy only, never a boundary claim - Malibu/Agoura/Westlake are LA County
insert into settings (key, value, updated_by) values ('business.brand_region', '"the 805"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 16 city pages exist and no others
insert into settings (key, value, updated_by) values ('service_area.booking_mode', '"listed_cities_only"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- never turn away a lead; let Josue decide
insert into settings (key, value, updated_by) values ('service_area.outside_area_behaviour', '"capture_lead_and_notify"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- -
insert into settings (key, value, updated_by) values ('pricing.currency', '"USD"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- no tax appears anywhere on the site
insert into settings (key, value, updated_by) values ('pricing.tax_mode', '"none"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- from his own pricing notes
insert into settings (key, value, updated_by) values ('pricing.quote_required_message', '"We''ll confirm your price after a quick look at your yard."'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'No sign-up fees.' His words. The capability exists; the default is off
insert into settings (key, value, updated_by) values ('billing.deposit_mode', '"none"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- as above
insert into settings (key, value, updated_by) values ('billing.deposit_amount_cents', '0'::jsonb, 'seed')
  on conflict (key) do nothing;
-- matches how a scooping round works
insert into settings (key, value, updated_by) values ('billing.charge_timing', '"after_visit"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- a weekly $15 charge is 4 Stripe fees a month; monthly is cheaper for him
insert into settings (key, value, updated_by) values ('billing.invoice_cadence', '"monthly"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- weekly service. One-time jobs over $99 ask for one
insert into settings (key, value, updated_by) values ('billing.card_on_file_required', 'false'::jsonb, 'seed')
  on conflict (key) do nothing;
-- protects him on big jobs without touching the weekly promise
insert into settings (key, value, updated_by) values ('billing.card_required_above_cents', '9900'::jsonb, 'seed')
  on conflict (key) do nothing;
-- how he is paid today. Stripe is ADDED, not substituted
insert into settings (key, value, updated_by) values ('billing.offline_methods', '["cash","venmo"]'::jsonb, 'seed')
  on conflict (key) do nothing;
-- Ben, 2026-09-10. 4%
insert into settings (key, value, updated_by) values ('billing.platform_fee_bps', '400'::jsonb, 'seed')
  on conflict (key) do nothing;
-- forced by the requirement that he can bring an existing Stripe account
insert into settings (key, value, updated_by) values ('billing.connect_account_type', '"standard"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- Ben, 2026-09-10: any day of the week
insert into settings (key, value, updated_by) values ('schedule.service_days', '[0,1,2,3,4,5,6]'::jsonb, 'seed')
  on conflict (key) do nothing;
-- Ben, 2026-09-10
insert into settings (key, value, updated_by) values ('schedule.day_start', '"07:00"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- Ben, 2026-09-10
insert into settings (key, value, updated_by) values ('schedule.day_end', '"17:00"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'Same day every week.' His core promise and a real routing constraint
insert into settings (key, value, updated_by) values ('schedule.same_day_every_week', 'true'::jsonb, 'seed')
  on conflict (key) do nothing;
-- his reviews praise exactly this. 'required' once there is enough crew
insert into settings (key, value, updated_by) values ('schedule.driver_consistency', '"preferred"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- an arrival window, not a time. Nothing on the site promises a time
insert into settings (key, value, updated_by) values ('schedule.visit_window_hours', '4'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'start within a few days, depending on route availability'
insert into settings (key, value, updated_by) values ('schedule.new_customer_start_days', '3'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'confirmed within 24 hours'
insert into settings (key, value, updated_by) values ('schedule.lead_response_hours', '24'::jsonb, 'seed')
  on conflict (key) do nothing;
-- his differentiator is proof of care, and it costs the crew four seconds
insert into settings (key, value, updated_by) values ('visit.require_completion_photo', 'true'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'Same-day text confirmation when complete.'
insert into settings (key, value, updated_by) values ('visit.completion_notify_channel', '"sms"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'No fees for skipping or pausing.'
insert into settings (key, value, updated_by) values ('visit.skip_charge_policy', '"no_charge"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'Just let us know in advance' - no number given, so none invented
insert into settings (key, value, updated_by) values ('visit.skip_notice_hours', '0'::jsonb, 'seed')
  on conflict (key) do nothing;
-- he drove there, but nothing on his site warns customers. Notify him; let him set a policy
insert into settings (key, value, updated_by) values ('visit.failed_access_policy', '"no_charge_notify_owner"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- the most sensitive value in this database
insert into settings (key, value, updated_by) values ('visit.gate_code_visible_to', '"assigned_crew_only"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'Never [a contract].'
insert into settings (key, value, updated_by) values ('subscription.min_term_visits', '0'::jsonb, 'seed')
  on conflict (key) do nothing;
-- 'Cancel anytime with no questions asked.'
insert into settings (key, value, updated_by) values ('subscription.cancel_notice_hours', '0'::jsonb, 'seed')
  on conflict (key) do nothing;
-- no published limit; a cap that stops a paused row living forever
insert into settings (key, value, updated_by) values ('subscription.pause_max_weeks', '12'::jsonb, 'seed')
  on conflict (key) do nothing;
-- pausing for vacation should not silently end service
insert into settings (key, value, updated_by) values ('subscription.auto_resume_after_pause', 'true'::jsonb, 'seed')
  on conflict (key) do nothing;
-- the current edge function
insert into settings (key, value, updated_by) values ('notify.lead_recipients', '["josue@scoopdogg.net","scoopdogg129@gmail.com"]'::jsonb, 'seed')
  on conflict (key) do nothing;
-- current; authenticates independently of his own SPF
insert into settings (key, value, updated_by) values ('notify.from_address', '"leads@mail.amtechleads.com"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- phone-first business
insert into settings (key, value, updated_by) values ('notify.customer_channel_default', '"sms"'::jsonb, 'seed')
  on conflict (key) do nothing;
-- the Uber comparison lives or dies on this
insert into settings (key, value, updated_by) values ('notify.on_the_way_enabled', 'true'::jsonb, 'seed')
  on conflict (key) do nothing;

do $$ declare n int; begin
  select count(*) into n from settings;
  if n <> 42 then raise exception 'expected 42 settings, found %', n; end if;
end $$;

commit;
