-- Scoop Dogg — take the prices out of the prose.
--
-- GENERATED by scripts/build-prose-price-migration.mjs from the live rows. Do not hand-edit;
-- regenerate. The down migration restores every original string byte for byte, which is the
-- whole reason this file is generated rather than typed.
--
-- Migration 013 moved the ladder to $90/$110/$130/$150 and the one-time work to $179/$269. These
-- 22 strings still carried the old numbers, and 16 of them are rendered into each city
-- page's FAQPage JSON-LD as well as its visible text - so a machine and a reader were both being
-- told a price the checkout would refuse.
--
-- The numbers are not updated. They are removed: the prose says how a price is worked out, the
-- rows say what it is, and gates/no-price-in-prose.mjs keeps them apart from here on.

-- rehearse: select count(*) = 0 from services where meta_description ~ '\$[0-9]' or intro ~ '\$[0-9]'
-- rehearse: select count(*) = 0 from (select jsonb_array_elements(faqs) e from service_areas) t where t.e->>'a' ~ '\$[0-9]'
-- rehearse: select count(*) = 0 from (select jsonb_array_elements(faqs) e from service_areas) t where t.e->>'q' ~ '\$[0-9]'
-- rehearse: select count(*) = 16 from service_areas
-- rehearse: select count(*) = 0 from (select jsonb_array_elements(faqs) e from service_areas) t where length(t.e->>'a') < 20

begin;

update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'agoura-hills';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'camarillo';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'carpinteria';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'fillmore';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'malibu';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'moorpark';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'newbury-park';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'oak-view';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'ojai';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'oxnard';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'santa-barbara';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'santa-paula';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'simi-valley';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'thousand-oaks';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'ventura';
update service_areas set faqs = jsonb_set(faqs, '{0,a}', to_jsonb($txt$Weekly scooping is priced by how many dogs you have, and the plans and their prices are on this page. One-time work — a deep clean, turf deodorizing or a dog run — is priced by the size of the area, and you see the number before you book, not after.$txt$::text)), updated_at = now()
 where slug = 'westlake-village';
update services set meta_description = $txt$Enzyme-based turf deodorizing that eliminates pet urine odor from artificial grass, gravel and concrete. Pet-safe, 100% natural, and priced by the size of the area.$txt$, updated_at = now() where slug = 'artificial-turf-deodorizing';
update services set meta_description = $txt$Full yard poop cleanup for overgrown or neglected yards. Perfect for moving, hosting, or getting back to zero. Priced by how much has built up. Ventura & Santa Barbara Counties.$txt$, updated_at = now() where slug = 'one-time-dog-poop-cleanup';
update services set meta_description = $txt$Scheduled weekly dog poop cleaning in Ventura & Santa Barbara Counties. We scoop, bag and haul off all waste, priced by how many dogs you have. Cancel anytime.$txt$, updated_at = now() where slug = 'weekly-pooper-scooper-service';
update services set intro = $txt$Our most popular service. We show up on the same day every week, walk your entire yard, scoop every pile, bag it, and haul it off your property. You never need to be home. Skip a week, pause for vacation, or cancel anytime. Plans are priced by how many dogs you have, and you see the price before you book.$txt$, updated_at = now() where slug = 'weekly-pooper-scooper-service';
update services set meta_description = $txt$Ongoing artificial turf sweeping and deodorizing. We use the SwipeSmith turf sweeper for leaf, debris and pet hair removal plus enzyme treatment. Priced by the size of the area.$txt$, updated_at = now() where slug = 'weekly-turf-maintenance';
update services set meta_description = $txt$Full turf and yard deep clean: brush, vacuum, pressure wash and heavy deodorizer. Ideal for seasonal resets and new homeowners. Priced by the size of the area.$txt$, updated_at = now() where slug = 'yard-deep-clean';

commit;
