-- Scoop Dogg — every postal code on a route, and every one we know and do not serve.
--
-- GENERATED by scripts/build-postal-codes.mjs on 2026-09-19. Do not hand-edit: re-run the script.
--
-- Source: https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_place20_natl.txt
-- (US Census Bureau, 2020 ZCTA-to-place relationship file. 91 rows matched our places.)
--
-- WHY A TABLE AND NOT THE CONSTANT. ZIP_CITY at src/components/booking/BookingFlow.tsx:49 held 30
-- pairs typed from memory: client-side only, no provenance, no server reader, and holes that each
-- send a real household to "somewhere else". Migration 013's lesson applies to geography too — a
-- fact the site depends on belongs in a row with a source and a date.
--
-- A ZCTA is a set of delivery routes, not a shape, so a ZIP can touch several places. The row
-- kept is the place sharing the most LAND with that ZCTA, except that a place we actually serve
-- beats one we do not: if we run a route there, that is the answer the customer needs.
--
-- 31 served ZIPs across 16 cities; 21 known and not served.
-- 31 rows are the business's own service claim; the rest are Census geography.
-- area_slug null means KNOWN AND NOT SERVED — the waitlist, and evidence about where the next
-- route day should go (P19 §4). It does not mean "never heard of", which is what a missing row is.

-- rehearse: select count(*) = 52 from area_postal_codes
-- rehearse: select count(*) = 31 from area_postal_codes where area_slug is not null
-- rehearse: select count(*) = 0 from service_areas s where s.bookable and s.status = 'active' and not exists (select 1 from area_postal_codes z where z.area_slug = s.slug)
-- rehearse: select count(*) = 0 from area_postal_codes where postal_code !~ '^[0-9]{5}$'
-- rehearse: select count(*) = 0 from (select postal_code from area_postal_codes group by postal_code having count(*) > 1) d
-- rehearse: select count(*) = 1 from area_postal_codes where postal_code = '93041' and area_slug is null
-- rehearse: select count(*) = 1 from area_postal_codes where postal_code = '91377' and area_slug is null
-- rehearse: select (select area_slug from area_postal_codes where postal_code = '93030') = 'oxnard'
-- rehearse: select (select area_slug from area_postal_codes where postal_code = '93001') = 'ventura'
-- rehearse: select count(*) = 21 from area_postal_codes where source = 'census-zcta520-place20-rel2020'
-- rehearse: select count(*) = 31 from area_postal_codes where source = 'business-claim:scoopdogg-service-area'
-- rehearse: select count(*) = 0 from area_postal_codes where source not in ('census-zcta520-place20-rel2020', 'business-claim:scoopdogg-service-area')
-- rehearse: select count(*) = 0 from area_postal_codes where area_slug is not null and source <> 'business-claim:scoopdogg-service-area'

begin;

create table area_postal_codes (
  postal_code  text primary key check (postal_code ~ '^[0-9]{5}$'),
  area_slug    text references service_areas(slug),   -- null = known, not served
  city_name    text not null,
  source       text not null,
  retrieved_on date not null,
  created_at   timestamptz not null default now()
);
create index area_postal_codes_area_idx on area_postal_codes (area_slug) where area_slug is not null;

comment on table area_postal_codes is
  'One row per postal code the business has an answer for. area_slug null is an ANSWER - "we '
  'know that ZIP and we are not on a route there yet" - and it routes the waitlist. A ZIP with '
  'no row at all is the only honest shrug.';

insert into area_postal_codes (postal_code, area_slug, city_name, source, retrieved_on) values
  ('90263', 'malibu', 'Pepperdine University CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('90265', 'malibu', 'Malibu city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('90290', null, 'Calabasas city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91301', 'agoura-hills', 'Agoura Hills city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('91302', null, 'Calabasas city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91311', null, 'Simi Valley city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91320', 'newbury-park', 'Thousand Oaks city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('91321', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91342', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91350', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91351', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91354', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91355', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91360', 'thousand-oaks', 'Thousand Oaks city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('91361', 'westlake-village', 'Thousand Oaks city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('91362', 'thousand-oaks', 'Thousand Oaks city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('91377', null, 'Oak Park CDP', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91381', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91384', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91387', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('91390', null, 'Santa Clarita city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93001', 'ventura', 'San Buenaventura (Ventura) city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93003', 'ventura', 'San Buenaventura (Ventura) city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93004', 'ventura', 'San Buenaventura (Ventura) city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93010', 'camarillo', 'Camarillo city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93012', 'camarillo', 'Camarillo city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93013', 'carpinteria', 'Toro Canyon CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93015', 'fillmore', 'Fillmore city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93021', 'moorpark', 'Moorpark city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93022', 'oak-view', 'Oak View CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93023', 'ojai', 'Mira Monte CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93030', 'oxnard', 'Oxnard city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93033', 'oxnard', 'Oxnard city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93035', 'oxnard', 'Oxnard city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93036', 'oxnard', 'Oxnard city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93040', null, 'Piru CDP', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93041', null, 'Port Hueneme city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93042', null, 'Oxnard city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93043', null, 'Port Hueneme city', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93060', 'santa-paula', 'Santa Paula city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93063', 'simi-valley', 'Simi Valley city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93065', 'simi-valley', 'Simi Valley city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93066', null, 'Somis CDP', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93067', null, 'Summerland CDP', 'census-zcta520-place20-rel2020', '2026-09-19'),
  ('93101', 'santa-barbara', 'Santa Barbara city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93103', 'santa-barbara', 'Santa Barbara city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93105', 'santa-barbara', 'Santa Barbara city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93108', 'santa-barbara', 'Montecito CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93109', 'santa-barbara', 'Santa Barbara city', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93110', 'santa-barbara', 'Eastern Goleta Valley CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93111', 'santa-barbara', 'Eastern Goleta Valley CDP', 'business-claim:scoopdogg-service-area', '2026-09-19'),
  ('93117', null, 'Goleta city', 'census-zcta520-place20-rel2020', '2026-09-19');

commit;
