-- Scoop Dogg — where the ZIPs actually are, so route density can stop being a feeling.
--
-- GENERATED by scripts/build-postal-geo.mjs on 2026-09-22. Do not hand-edit: re-run the script.
--
-- Source: https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2020_Gazetteer/2020_Gaz_zcta_national.zip
-- (US Census Bureau, 2020 ZCTA Gazetteer. Internal point and land area, 52 rows matched.)
--
-- WHY THIS EXISTS. Migration 020 answered WHICH ZIPs are on a route and made the funnel's first
-- question answerable from rows. It could not answer the question underneath it: what it COSTS to
-- serve one. Nothing on this project has ever held a coordinate, so nothing on this project could
-- tell the difference between a customer four miles away and one thirty-four miles away.
--
-- That difference is not small and it is not linear. The Beardwood-Halton-Hammersley result, and
-- Daganzo's distribution form of it, give the length of a good route through n stops scattered in
-- an area A at distance r from the depot as roughly
--
--     distance  ~=  2r  +  k * sqrt(n * A)
--
-- so the DRIVING PER STOP is (2r + k*sqrt(nA)) / n, which falls like 1/n in the line-haul term
-- and like 1/sqrt(n) in the local one. The consequence is the whole reason for this migration:
-- the cost of serving a city is a function of how many customers are already in it, so "where
-- should the next customer come from" has an arithmetic answer, and the answer changes as the
-- book of business changes. server/lib/density.ts is that arithmetic.
--
-- WHAT IS A FACT HERE AND WHAT IS A MODEL, kept apart on purpose:
--
--   FACT     the coordinates and land areas below (Census, with the URL and the date)
--   FACT     the depot, from Google's own placement of Scoop Dogg (see below)
--   MODEL    the two speeds and the circuity factor, which are defaults with reasons
--   UNKNOWN  what an hour of Josue's time and a mile of his van cost. NOT SEEDED, deliberately.
--
-- The last line is the one that matters. It would be easy to put a plausible $25/hour in a row
-- and start printing dollar margins per city, and every one of them would be a number about a
-- business nobody asked. So `routing.cost_per_hour_cents` is absent, density.ts reports
-- `measured: false` for anything denominated in money, and the output that needs no cost at all
-- — DRIVING MINUTES PER VISIT, against the service minutes already recorded on every tier — is
-- the number the admin shows. It is enough to rank cities, which is the decision.
--
-- THE DEPOT. Josue's site links his Google Maps place from the footer and every /areas page; that
-- link resolves to `@34.2954755,-119.2912215`, which is Google's own placement of the business.
-- It is the best-evidenced origin available without asking him where he keeps the van, and when he
-- says, it is one row. `node scripts/derive-place-id.mjs` prints the same resolution.

-- rehearse: select count(*) = 52 from area_postal_codes where latitude is not null and longitude is not null
-- rehearse: select count(*) = 0 from area_postal_codes where latitude is null
-- rehearse: select count(*) = 0 from area_postal_codes where area_slug is not null and (latitude not between 33.5 and 35.2 or longitude not between -120.7 and -118)
-- rehearse: select count(*) = 0 from area_postal_codes where land_sq_mi is null or land_sq_mi <= 0
-- rehearse: select count(*) = 0 from area_postal_codes where geo_source <> 'census-gazetteer-zcta-2020'
-- rehearse: select count(*) = 3 from settings where key in ('routing.depot_lat', 'routing.depot_lon', 'routing.road_circuity')
-- rehearse: select count(*) = 0 from settings where key = 'routing.cost_per_hour_cents'
-- rehearse: select (select value::numeric from settings where key = 'routing.depot_lat') between 33.5 and 35.2
-- rehearse: select (select value::numeric from settings where key = 'routing.road_circuity') between 1.0 and 2.0

begin;

alter table area_postal_codes
  add column latitude         numeric(9, 6),
  add column longitude        numeric(9, 6),
  add column land_sq_mi       numeric(10, 3),
  add column geo_source       text,
  add column geo_retrieved_on date;

comment on column area_postal_codes.latitude is
  'Census internal point: a representative coordinate INSIDE the ZCTA, not a population centroid '
  'and not a mailing address. Good enough to rank cities by distance, not good enough to route a '
  'van between two houses.';

update area_postal_codes z
   set latitude = g.lat, longitude = g.lon, land_sq_mi = g.land,
       geo_source = 'census-gazetteer-zcta-2020', geo_retrieved_on = '2026-09-22'
  from (values
  ('90263', 34.039034, -118.707992, 0.226),
  ('90265', 34.066117, -118.846342, 107.779),
  ('90290', 34.107752, -118.616218, 20.048),
  ('91301', 34.123286, -118.758541, 34.069),
  ('91302', 34.122556, -118.669821, 26.709),
  ('91311', 34.292495, -118.602424, 32.076),
  ('91320', 34.175968, -118.945091, 18.238),
  ('91321', 34.368158, -118.489130, 25.884),
  ('91342', 34.326584, -118.382261, 55.303),
  ('91350', 34.434623, -118.500092, 16.950),
  ('91351', 34.433727, -118.458061, 9.571),
  ('91354', 34.464816, -118.553871, 8.725),
  ('91355', 34.440082, -118.644055, 15.497),
  ('91360', 34.212718, -118.882132, 14.455),
  ('91361', 34.136003, -118.888634, 33.513),
  ('91362', 34.193336, -118.818692, 19.630),
  ('91377', 34.184974, -118.766912, 5.293),
  ('91381', 34.384728, -118.647334, 37.615),
  ('91384', 34.506627, -118.699048, 108.558),
  ('91387', 34.402519, -118.363463, 49.523),
  ('91390', 34.545587, -118.420095, 143.120),
  ('93001', 34.058607, -119.929120, 205.155),
  ('93003', 34.283668, -119.223196, 20.579),
  ('93004', 34.278679, -119.165615, 7.045),
  ('93010', 34.227888, -119.079553, 22.133),
  ('93012', 34.196026, -118.992531, 52.723),
  ('93013', 34.440133, -119.503306, 56.944),
  ('93015', 34.404100, -118.897777, 76.564),
  ('93021', 34.303596, -118.889583, 47.015),
  ('93022', 34.407780, -119.306554, 4.621),
  ('93023', 34.529879, -119.310238, 270.144),
  ('93030', 34.205336, -119.174835, 14.021),
  ('93033', 34.150203, -119.127727, 29.313),
  ('93035', 34.181650, -119.223902, 4.055),
  ('93036', 34.237254, -119.184449, 15.599),
  ('93040', 34.473884, -118.797181, 70.596),
  ('93041', 34.106028, -119.098081, 11.102),
  ('93042', 33.255655, -119.503588, 22.639),
  ('93043', 34.170854, -119.202409, 0.482),
  ('93060', 34.402197, -119.094893, 118.914),
  ('93063', 34.308048, -118.686969, 32.968),
  ('93065', 34.258405, -118.775026, 31.665),
  ('93066', 34.297699, -119.014558, 41.581),
  ('93067', 34.421964, -119.593483, 0.589),
  ('93101', 34.418979, -119.709167, 3.430),
  ('93103', 34.437367, -119.679284, 5.242),
  ('93105', 34.533222, -119.791731, 97.128),
  ('93108', 34.448024, -119.616984, 21.201),
  ('93109', 34.406408, -119.726927, 3.385),
  ('93110', 34.446201, -119.762794, 10.546),
  ('93111', 34.449185, -119.804782, 8.107),
  ('93117', 34.479453, -120.084094, 170.077)
       ) as g(zip, lat, lon, land)
 where z.postal_code = g.zip;

-- Every existing row got geometry, or this migration is wrong about its own source.
do $$
declare n int;
begin
  select count(*) into n from area_postal_codes where latitude is null;
  if n > 0 then raise exception 'area_postal_codes: % rows have no coordinate', n; end if;
end $$;

alter table area_postal_codes
  alter column latitude   set not null,
  alter column longitude  set not null,
  alter column land_sq_mi set not null,
  alter column geo_source set not null;

insert into settings (key, value, updated_by) values
  -- Google's own placement of the business, from the Maps link the site already publishes.
  ('routing.depot_lat',      '34.2954755'::jsonb,                    'migration:031'),
  ('routing.depot_lon',      '-119.2912215'::jsonb,                  'migration:031'),
  ('routing.depot_source',   '"google-maps-place:ChIJx2f0lVCt6YARL_qslmyUQKM"'::jsonb, 'migration:031'),
  -- Road distance / straight-line distance. 1.2-1.4 is the usual range for US metros; 1.3 is the
  -- middle of it. A model constant, not a measurement of Ventura County.
  ('routing.road_circuity',  '1.30'::jsonb,                          'migration:031'),
  -- Depot-to-area and stop-to-stop. Both are defaults to be replaced the first time anybody
  -- times a real route day, which is the point of writing them down as rows.
  ('routing.speed_linehaul_mph', '40'::jsonb,                        'migration:031'),
  ('routing.speed_local_mph',    '22'::jsonb,                        'migration:031'),
  -- The BHH/Daganzo local-tour constant. 0.7124 is the asymptotic value for an optimal tour over
  -- uniformly scattered points; 0.75 leaves a little room for a route that is good, not optimal.
  ('routing.bhh_k',              '0.75'::jsonb,                      'migration:031')
on conflict (key) do nothing;

-- DELIBERATELY NOT SEEDED: routing.cost_per_hour_cents, routing.cost_per_mile_cents.
-- Nobody has asked Josue what his hour or his mile costs. Until somebody does, density.ts
-- reports every money figure as unmeasured and ranks on time instead.

commit;
