-- Scoop Dogg — where the CUSTOMERS are, which is not where the polygon is.
--
-- GENERATED by scripts/build-postal-centroids.mjs on 2026-09-23. Do not hand-edit: re-run the script.
--
-- Sources, both US Census Bureau, 2020:
--   https://www2.census.gov/geo/docs/reference/cenpop2020/tract/CenPop2020_Mean_TR06.txt
--   https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_tract20_natl.txt
--
-- WHAT 031 GOT WRONG, AND IT SAID SO ITSELF. Migration 031 wrote the ZCTA internal point and gave
-- the column this comment: "a representative coordinate INSIDE the ZCTA, not a population
-- centroid and not a mailing address". server/lib/density.ts then used it as where the customers
-- are. For a compact suburb that is nearly true. For ZCTA 93001 — Ventura PLUS the Channel
-- Islands, 205.2 sq mi — the internal point lands at 34.0586,-119.9291, in the ocean, and put the
-- depot's own city 40.0 miles from a depot that is inside it. The growth board's
-- "where should the next customer come from" ranked Ventura as the most expensive city in the
-- network to serve. Ojai 93023 (270.1 sq mi) had it from the mountains, Goleta 93117 (170.1) from
-- Gaviota, Santa Barbara 93105 (97.1) from the back country, Malibu 90265 (107.8) from the canyons.
--
-- THE AREA WAS WRONG THE SAME WAY, and that is half the error. density.ts scatters n stops across
-- area A in the Beardwood-Halton-Hammersley term k*sqrt(n*A). Stops are scattered where the PEOPLE
-- are. Using the polygon's land area overstates the local driving by sqrt(A_polygon / A_populated)
-- — about 3.7x for 93001 — in every city with an empty half.
--
-- SO THERE ARE TWO NEW COLUMNS AND THE OLD ONES ARE UNTOUCHED. `latitude`, `longitude` and
-- `land_sq_mi` remain exactly what 031 wrote: the correct answer to "where is this polygon and
-- how big is it". The new columns answer "where are the people in it and how much ground do they
-- cover", and a reader can see both and tell which one a number came from.
--
--   populated_lat/lon  population-weighted centroid of the tract centres of population in the ZCTA
--   populated_sq_mi    the area that population occupies, from the Census's own population-weighted
--                      density d = sum(p*p/a)/sum(p), inverted: A = sum(p)^2 / sum(p^2/a)
--   population         the apportioned 2020 count, so a reader can see what the weight was
--
-- THE ONE APPROXIMATION, named. A tract wholly inside a ZCTA contributes all of its population at
-- its own centre of population, and that is exact. A tract straddling the boundary is split by
-- land area (AREALAND_PART / AREALAND_TRACT), because nothing finer is published at this level.
-- The residual error is areal apportionment inside a straddling tract, and it is second order:
-- the Channel Islands tracts fall out of 93001 by carrying almost no people, not by any rule.
--
-- WHAT THIS DOES NOT CLAIM. It is not a routing geocode. It is the centre of where customers can
-- be, which is what ranks cities; it is not good enough to drive a van between two houses, and
-- density.ts has never claimed otherwise.
--
-- MEASURED ON GENERATION (2026-09-23):
--   nearest served   93001 ventura at 0.3 mi (031 said 40.0)
--   farthest served  90263 malibu at 37.2 mi (031 said 37.8)
--   network span     67.8 mi, 93111 to 90263 (031's figure was 73.1)

-- rehearse: select count(*) = 52 from area_postal_codes where populated_lat is not null and populated_lon is not null
-- rehearse: select count(*) = 0 from area_postal_codes where area_slug is not null and populated_lat is null
-- rehearse: select count(*) = 0 from area_postal_codes where populated_sq_mi is not null and populated_sq_mi <= 0
-- rehearse: select count(*) = 0 from area_postal_codes where populated_sq_mi is not null and zcta2020_sq_mi is not null and populated_sq_mi > zcta2020_sq_mi * 1.001
-- rehearse: select count(*) = 5 from area_postal_codes where populated_lat is not null and populated_sq_mi is null
-- rehearse: select count(*) = 0 from area_postal_codes where population is not null and population < 0
-- rehearse: select count(*) = 0 from area_postal_codes where populated_geo_source is not null and populated_geo_source <> 'census-cenpop-tract-2020+zcta-tract-rel-2020'
-- rehearse: select count(*) = 0 from area_postal_codes where area_slug is not null and 3958.8 * 2 * asin(sqrt(power(sin(radians(populated_lat - 34.2954755) / 2), 2) + cos(radians(34.2954755)) * cos(radians(populated_lat)) * power(sin(radians(populated_lon - (-119.2912215)) / 2), 2))) > 70
-- rehearse: select 3958.8 * 2 * asin(sqrt(power(sin(radians(populated_lat - 34.2954755) / 2), 2) + cos(radians(34.2954755)) * cos(radians(populated_lat)) * power(sin(radians(populated_lon - (-119.2912215)) / 2), 2))) < 8 from area_postal_codes where postal_code = '93003'

begin;

alter table area_postal_codes
  add column populated_lat        numeric(9, 6),
  add column populated_lon        numeric(9, 6),
  add column populated_sq_mi      numeric(10, 3),
  add column zcta2020_sq_mi       numeric(10, 3),
  add column population           integer,
  add column populated_tracts     integer,
  add column populated_geo_source text,
  add column populated_retrieved_on date;

comment on column area_postal_codes.populated_lat is
  'Population-weighted centroid: where the PEOPLE in this ZCTA are, assembled from Census tract '
  'centres of population. Use this for anything that models where customers are. `latitude` is '
  'the polygon''s internal point and is a different fact — 93001''s is in the ocean.';
comment on column area_postal_codes.populated_sq_mi is
  'The area that population occupies, from the Census population-weighted density inverted: '
  'sum(p)^2 / sum(p^2/a). This is the A in the BHH local-tour term, because stops are scattered '
  'where people are and not across the polygon. `land_sq_mi` is the whole polygon and for 93001 '
  'is 205.2 against a populated 8.9.';

update area_postal_codes z
   set populated_lat = g.lat, populated_lon = g.lon, populated_sq_mi = g.area,
       zcta2020_sq_mi = g.zcta_area, population = g.pop, populated_tracts = g.tracts,
       populated_geo_source = 'census-cenpop-tract-2020+zcta-tract-rel-2020', populated_retrieved_on = '2026-09-23'
  from (values
  ('90263', 34.043526, -118.716628, null, 0.234, 63, 2),
  ('90265', 34.049398, -118.758207, 37.894, 111.010, 17914, 9),
  ('90290', 34.103769, -118.607709, 14.643, 18.725, 7238, 5),
  ('91301', 34.146549, -118.761707, 9.421, 33.117, 25394, 8),
  ('91302', 34.140168, -118.660565, 11.735, 27.450, 25385, 12),
  ('91311', 34.255957, -118.593867, 7.027, 32.564, 41252, 21),
  ('91320', 34.178152, -118.939458, 13.280, 20.176, 44361, 12),
  ('91321', 34.383496, -118.510744, 6.560, 26.659, 37715, 14),
  ('91342', 34.305001, -118.435236, 9.949, 45.445, 96830, 31),
  ('91350', 34.437161, -118.507353, 8.302, 15.866, 37059, 17),
  ('91351', 34.424429, -118.475812, 5.283, 8.686, 33142, 14),
  ('91354', 34.450229, -118.550364, 5.157, 7.327, 26982, 8),
  ('91355', 34.414341, -118.557328, 7.982, 13.154, 40700, 12),
  ('91360', 34.209568, -118.872595, 11.562, 15.363, 43702, 13),
  ('91361', 34.150207, -118.844594, 7.834, 28.867, 16808, 7),
  ('91362', 34.191743, -118.826690, 11.580, 18.989, 36666, 9),
  ('91377', 34.179988, -118.774622, 3.063, 5.395, 9130, 4),
  ('91381', 34.390048, -118.588861, 13.389, 39.528, 19425, 3),
  ('91384', 34.467983, -118.621052, 12.061, 103.601, 24969, 10),
  ('91387', 34.420045, -118.429253, 4.210, 53.421, 38393, 14),
  ('91390', 34.472147, -118.464540, 17.520, 158.124, 30244, 11),
  ('93001', 34.293756, -119.286538, 8.903, 96.585, 37236, 13),
  ('93003', 34.269699, -119.219971, 8.626, 20.785, 48206, 16),
  ('93004', 34.278408, -119.169201, 5.515, 7.029, 29016, 8),
  ('93010', 34.231378, -119.049915, 8.138, 21.972, 43394, 13),
  ('93012', 34.222610, -118.993474, 10.463, 50.138, 40244, 10),
  ('93013', 34.401940, -119.519619, 5.425, 41.381, 15938, 6),
  ('93015', 34.400931, -118.918808, 61.738, 92.788, 16508, 4),
  ('93021', 34.276004, -118.872700, 12.564, 47.791, 37300, 13),
  ('93022', 34.408988, -119.295729, 2.092, 3.139, 4859, 4),
  ('93023', 34.435137, -119.238720, 20.362, 266.868, 22462, 10),
  ('93030', 34.204183, -119.174040, 6.032, 14.113, 58075, 19),
  ('93033', 34.168758, -119.171017, 5.827, 32.195, 78725, 23),
  ('93035', 34.186708, -119.215878, 3.208, 5.029, 26793, 10),
  ('93036', 34.230724, -119.174957, 7.215, 17.799, 50890, 18),
  ('93040', 34.457623, -118.877168, null, 372.119, 1309, 2),
  ('93041', 34.162525, -119.196701, 2.186, 5.879, 22143, 7),
  ('93042', 34.123905, -119.097579, 4.908, 27.547, 1075, 1),
  ('93043', 34.162472, -119.200270, null, 0.495, 378, 1),
  ('93060', 34.352417, -119.079337, 7.521, 92.447, 37150, 13),
  ('93063', 34.279290, -118.699781, 10.187, 36.167, 52412, 16),
  ('93065', 34.265038, -118.767617, 12.909, 29.802, 65019, 19),
  ('93066', 34.274652, -118.993275, null, 42.083, 5784, 2),
  ('93067', 34.418755, -119.553410, null, 0.581, 56, 1),
  ('93101', 34.419533, -119.709584, 2.441, 3.202, 28429, 14),
  ('93103', 34.428749, -119.683321, 2.326, 5.490, 18540, 8),
  ('93105', 34.442675, -119.731798, 7.123, 139.755, 29672, 15),
  ('93108', 34.431921, -119.631367, 10.680, 27.858, 9741, 7),
  ('93109', 34.408055, -119.721281, 2.941, 3.433, 13693, 6),
  ('93110', 34.440738, -119.769458, 3.993, 8.085, 16485, 5),
  ('93111', 34.439456, -119.802790, 3.763, 8.135, 17957, 9),
  ('93117', 34.430997, -119.870280, 4.458, 168.080, 54631, 18)
       ) as g(zip, lat, lon, area, zcta_area, pop, tracts)
 where z.postal_code = g.zip;

-- Every ZIP ON A ROUTE got a populated centre, or this migration is wrong about its own source.
-- A not-served ZIP may legitimately have none: 93042 is San Nicolas Island.
do $$
declare n int;
begin
  select count(*) into n from area_postal_codes where area_slug is not null and populated_lat is null;
  if n > 0 then raise exception 'area_postal_codes: % served rows have no populated centre', n; end if;
end $$;

commit;
