export interface CityData {
  name: string;
  slug: string;
  tier: 1 | 2 | 3;
  region: 'ventura-county' | 'nearby';
  parentCity?: string;
  intro: string;
  neighborhoods: string[];
  nearbySlug: string[];
  faqs: { q: string; a: string }[];
  metaTitle: string;
  metaDescription: string;
  localContext: string;
  testimonial: {
    quote: string;
    name: string;
    city: string;
  };
}

export const CITIES: CityData[] = [
  {
    name: 'Ventura',
    slug: 'ventura',
    tier: 1,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Ventura, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Ventura, CA. Serving Midtown, Ventura Harbor, and surrounding neighborhoods. Weekly & one-time service.',
    intro: 'Ventura is a vibrant coastal city where dogs and their owners love exploring the area near Ventura Harbor, walking the promenade by Ventura Pier, or hanging out around Pacific View Mall. Scoop Dogg keeps yards in Midtown and throughout Ventura clean so you can spend more time enjoying this beautiful community — not cleaning up after your pets.',
    neighborhoods: ['Midtown', 'Ventura Harbor Village', 'Eastside', 'Westside', 'Ondulando', 'Pierpont Beach', 'Montalvo'],
    nearbySlug: ['oxnard', 'camarillo', 'ojai', 'carpinteria'],
    localContext: "Ventura's coastal climate keeps yards damp year-round, which means waste breaks down more slowly and odors linger longer than you'd expect. Whether you're near the beach where salt air keeps things humid, or up in the hills off Foothill Road where larger lots mean more ground to cover, Scoop Dogg adapts to your property. Most of our Ventura clients are on a weekly Tuesday or Thursday route, and we typically confirm your start date within 24 hours of booking.",
    testimonial: {
      quote: "Best money I spend every month. My yard has never looked better.",
      name: "Diana K.",
      city: "Ventura",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Ventura?', a: 'Weekly yard cleanup is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. We confirm all pricing before your first visit.' },
      { q: 'What days do you service Ventura?', a: 'We run dedicated Ventura routes on Tuesdays and Thursdays. Your specific day is confirmed when you book, and we stick to the same day every week.' },
      { q: 'Do I need to be home when you come?', a: 'No — you never need to be home. Just make sure we have gate access. Leave any codes or instructions in the notes when you book and we handle everything, then secure the gate behind us.' },
      { q: 'Do you service the Ventura Harbor and beach neighborhoods?', a: 'Yes. We cover all of Ventura including Harbor Village, Pierpont Beach, Midtown, Eastside, Westside, Ondulando, and Montalvo.' },
      { q: 'How do I get started with service in Ventura?', a: 'Book online in 60 seconds using the form on this page, or call us at (805) 869-8070. We confirm your schedule the same day and can typically start within a few days.' },
    ],
  },
  {
    name: 'Ojai',
    slug: 'ojai',
    tier: 2,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Ojai, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Ojai, CA. Serving Downtown Ojai, Ojai Valley, and Meiners Oaks. Weekly & one-time service.',
    intro: "Ojai's serene Ojai Valley and the charming streets of Downtown Ojai make it one of Ventura County's most beloved communities. With acres of trails and open spaces nearby, dogs in Ojai get plenty of exercise — which means yards need regular attention. Scoop Dogg handles the mess in Meiners Oaks and throughout the valley so you can enjoy Ojai's peaceful lifestyle.",
    neighborhoods: ['Downtown Ojai', 'Meiners Oaks', 'Ojai Valley Estates', 'East Ojai', 'Upper Ojai', 'Signal Street area'],
    nearbySlug: ['oak-view', 'ventura', 'santa-paula'],
    localContext: "Ojai's inland valley location means warm, dry summers and occasional heavy rains in winter — conditions that create their own yard maintenance challenges. Many properties here have mature landscaping, fruit trees, and sloped terrain that make DIY cleanup a real chore. Most of our Ojai clients are on a Monday or Wednesday route, and because lots in the valley tend to run larger, we give each property the time it needs. We confirm your start date within 24 hours of booking.",
    testimonial: {
      quote: "I have three dogs and a big yard. Scoop Dogg is the only thing that keeps it manageable.",
      name: "Robert M.",
      city: "Ojai",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Ojai?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing is confirmed based on your yard size and number of dogs.' },
      { q: 'What days do you service Ojai?', a: 'We run Ojai routes on Mondays and Wednesdays. Your day is locked in when you book and stays the same every week.' },
      { q: 'Do I need to be home when you come?', a: 'Not at all. Leave gate access in your booking notes and we take care of everything. We always secure the gate when we leave.' },
      { q: 'My yard has a lot of trees and landscaping — is that a problem?', a: 'Not at all. We navigate all yard types including landscaped gardens, wooded areas, and sloped terrain common in the Ojai Valley.' },
      { q: 'How do I get started with service in Ojai?', a: 'Book online in 60 seconds using the form on this page, or call (805) 869-8070. We confirm same day and can typically start within a few days.' },
    ],
  },
  {
    name: 'Oak View',
    slug: 'oak-view',
    tier: 3,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Oak View, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Oak View, CA. Small community near Ojai. Weekly & one-time service.',
    intro: 'Oak View is a tight-knit community tucked just outside of Ojai, known for its rural feel and dog-friendly properties. Many homes here have generous yards and multiple pets, making regular waste removal especially important. Scoop Dogg provides dependable, friendly service to Oak View households so your outdoor space stays fresh year-round.',
    neighborhoods: ['Oak View', 'Casitas Springs area', 'Highway 33 corridor', 'Foothill Road area'],
    nearbySlug: ['ojai', 'ventura', 'santa-paula'],
    localContext: "Oak View's rural character means most properties have large yards — and with more space comes more ground to cover. Many homeowners here have multiple dogs and rarely have time to keep up with cleanup on bigger lots. We serve Oak View on our Monday and Wednesday inland routes, pairing it efficiently with nearby Ojai. Because the community is small and tight-knit, we treat every property like a neighbor's — and we confirm your start date within 24 hours of booking.",
    testimonial: {
      quote: "We have two big dogs and a large yard. Scoop Dogg handles it every week without us even thinking about it.",
      name: "Mark T.",
      city: "Oak View",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Oak View?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. We confirm exact pricing based on yard size and dog count.' },
      { q: 'What days do you service Oak View?', a: 'Oak View is on our Monday and Wednesday inland route. Your specific day is confirmed at booking.' },
      { q: 'Do I need to be home when you come?', a: 'No. Just leave gate access details in your booking notes and we handle everything, securing the gate when we leave.' },
      { q: 'What if I have a large rural property?', a: 'We size our service to your yard. Large property? No problem — just select "large" when booking and we take care of everything.' },
      { q: 'How do I get started in Oak View?', a: 'Use the booking form on this page or call (805) 869-8070. We confirm same day and typically start within a few days.' },
    ],
  },
  {
    name: 'Oxnard',
    slug: 'oxnard',
    tier: 1,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Oxnard, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Oxnard, CA. Serving The Collection, Channel Islands Harbor, Riverpark, and all neighborhoods.',
    intro: "Oxnard is Ventura County's largest city, home to beautiful neighborhoods near Channel Islands Harbor, the family-friendly Riverpark community, and the popular Collection at RiverPark shopping district. With so many dog owners across Oxnard's diverse neighborhoods, Scoop Dogg offers reliable, scheduled service to keep every yard in top shape.",
    neighborhoods: ['Riverpark', 'Channel Islands Harbor', 'Colonia', 'Silver Strand', 'El Rio', 'Oxnard Shores', 'Hollywood Beach'],
    nearbySlug: ['ventura', 'camarillo', 'santa-paula'],
    localContext: "Oxnard spans a lot of ground, from the coastal neighborhoods near Hollywood Beach and Silver Strand to the newer master-planned streets of Riverpark. Coastal yards tend to stay damp and are more prone to odor buildup, while inland Oxnard properties often feature artificial turf that needs enzyme treatment to stay fresh. We run Oxnard routes on Tuesdays and Fridays, and with so many clients in the city we can usually get new customers started within 48 hours of booking.",
    testimonial: {
      quote: "Reliable, professional, and they actually show up every single week. Game changer.",
      name: "Carmen L.",
      city: "Oxnard",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Oxnard?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Final pricing depends on yard size and dog count.' },
      { q: 'What days do you service Oxnard?', a: 'We run Oxnard routes on Tuesdays and Fridays. Your day is locked in at booking and stays consistent every week.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave any gate codes or access info in the notes field when booking. We handle everything and secure the gate when we leave.' },
      { q: 'Do you cover all of Oxnard including the harbor and beach areas?', a: 'Yes — we service all Oxnard neighborhoods including Channel Islands Harbor, Riverpark, Hollywood Beach, Oxnard Shores, Silver Strand, and more.' },
      { q: 'How do I get started in Oxnard?', a: 'Book online in 60 seconds using the form on this page, or call (805) 869-8070. We confirm same day and can start within a couple days.' },
    ],
  },
  {
    name: 'Camarillo',
    slug: 'camarillo',
    tier: 1,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Camarillo, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Camarillo, CA. Serving Constitution Park, Leisure Village, Spanish Hills, and all neighborhoods.',
    intro: "Camarillo is one of Ventura County's most beloved cities, with pristine neighborhoods near Constitution Park, the well-known Leisure Village retirement community, and upscale Spanish Hills. Dog owners throughout Camarillo trust Scoop Dogg to keep their yards spotless so they can enjoy the area's excellent parks and community spaces.",
    neighborhoods: ['Spanish Hills', 'Leisure Village', 'Mission Oaks', 'Camarillo Heights', 'Las Posas Estates', 'Springville'],
    nearbySlug: ['oxnard', 'ventura', 'thousand-oaks', 'moorpark'],
    localContext: "Camarillo's well-kept neighborhoods and HOA-managed communities mean curb appeal matters — and that extends to backyards. Many homes in Spanish Hills and Las Posas Estates have larger lots with mature landscaping, while Mission Oaks and Springville feature smaller yards that still need consistent weekly attention. We run Camarillo routes on Wednesdays and Fridays, and with a large client base in the city we can usually confirm your start date within 24 hours of booking.",
    testimonial: {
      quote: "I live in a 55+ community and this service has been a lifesaver. They're always on time and so professional.",
      name: "Patricia W.",
      city: "Camarillo",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Camarillo?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing is based on yard size and number of dogs.' },
      { q: 'What days do you service Camarillo?', a: 'We run Camarillo routes on Wednesdays and Fridays. Your day is confirmed when you book and stays the same every week.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes. We handle everything and always secure the gate when we leave.' },
      { q: 'Do you service Leisure Village and other 55+ communities in Camarillo?', a: 'Yes — Leisure Village is one of our regular service areas. We work with many residents in HOA and 55+ communities throughout Ventura County.' },
      { q: 'How do I get started in Camarillo?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can typically start within a few days.' },
    ],
  },
  {
    name: 'Santa Paula',
    slug: 'santa-paula',
    tier: 2,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Santa Paula, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Santa Paula, CA. Serving Downtown Santa Paula and surrounding areas.',
    intro: "Santa Paula is a charming agricultural city with deep roots in Ventura County's citrus heritage. Nestled in the Santa Clara River Valley, this friendly community has a strong sense of neighborhood pride — and Scoop Dogg helps keep it that way, one yard at a time. From Downtown Santa Paula to the surrounding residential areas, we're proud to serve this hardworking community.",
    neighborhoods: ['Downtown Santa Paula', 'Eastside', 'Westside', 'Foothill area', 'Citrus Way corridor'],
    nearbySlug: ['ojai', 'oak-view', 'ventura', 'oxnard'],
    localContext: "Santa Paula sits in the Santa Clara River Valley where warm inland temperatures and agricultural surroundings mean yards dry out quickly in summer. Many properties here have older, more character-filled lots — fruit trees, uneven terrain, and established landscaping that takes extra care to navigate. We service Santa Paula on our Monday and Thursday inland routes, and new customers can typically get started within a few days of booking.",
    testimonial: {
      quote: "Super friendly, very thorough. My yard looks cleaner than it ever did when I was doing it myself.",
      name: "Angela R.",
      city: "Santa Paula",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Santa Paula?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. We confirm final pricing based on your yard and dog count.' },
      { q: 'What days do you service Santa Paula?', a: 'Santa Paula is on our Monday and Thursday inland route. Your day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Just leave gate access details in your booking notes. We take care of everything and secure the gate when we leave.' },
      { q: 'Do you service yards with citrus trees or uneven terrain?', a: 'Absolutely. We navigate all yard types and love the character of Santa Paula\'s older properties — fruit trees, slopes, and all.' },
      { q: 'How do I get started in Santa Paula?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a couple days.' },
    ],
  },
  {
    name: 'Thousand Oaks',
    slug: 'thousand-oaks',
    tier: 1,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Thousand Oaks, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Thousand Oaks, CA. Serving Conejo Valley, The Oaks Mall area, Wildwood Park, and all neighborhoods.',
    intro: "Thousand Oaks is consistently ranked among the safest and most desirable cities in California, with stunning Conejo Valley scenery, Wildwood Park trails, and thriving neighborhoods near The Oaks Mall. Dog ownership is a way of life here, and Scoop Dogg provides the reliable, professional service that Thousand Oaks residents expect.",
    neighborhoods: ['Conejo Valley', 'Lang Ranch', 'Wildwood', 'Dos Vientos (east side)', 'Oakbrook', 'Lynn Ranch', 'Sunset Hills'],
    nearbySlug: ['newbury-park', 'camarillo', 'moorpark', 'simi-valley'],
    localContext: "Thousand Oaks has one of the highest concentrations of dog owners in Ventura County, and many neighborhoods — particularly Lang Ranch, Oakbrook, and Lynn Ranch — feature larger lots with significant yard space. Artificial turf is increasingly common in newer builds, and enzyme deodorizing is a popular add-on for those clients. We run Thousand Oaks routes on Tuesdays and Thursdays, and because of our volume here, we can usually confirm new customers within 24 hours and start within the week.",
    testimonial: {
      quote: "We have two labs and an acre of yard. Scoop Dogg handles it every week — I don't even think about it anymore.",
      name: "Kevin S.",
      city: "Thousand Oaks",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Thousand Oaks?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. We confirm pricing based on yard size and number of dogs.' },
      { q: 'What days do you service Thousand Oaks?', a: 'We run Thousand Oaks routes on Tuesdays and Thursdays. Your day is confirmed at booking and stays consistent.' },
      { q: 'Do I need to be home when you come?', a: 'No. Provide gate access in your booking notes and we handle everything, securing the gate when we leave.' },
      { q: 'Do you work in gated communities in Thousand Oaks?', a: 'Yes — we work with gated communities regularly. Provide gate codes or HOA access info in the notes section when booking.' },
      { q: 'How do I get started in Thousand Oaks?', a: 'Book online in 60 seconds using the form on this page, or call (805) 869-8070. We confirm same day.' },
    ],
  },
  {
    name: 'Newbury Park',
    slug: 'newbury-park',
    tier: 2,
    region: 'ventura-county',
    parentCity: 'thousand-oaks',
    metaTitle: 'Dog Poop Cleaning in Newbury Park, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Newbury Park, CA. Serving Dos Vientos, Borchard Community Center area, and all neighborhoods.',
    intro: "Newbury Park sits at the western edge of Thousand Oaks, with gorgeous master-planned neighborhoods like Dos Vientos and active community spaces near Borchard Community Center. Families with dogs love this area's wide streets and open parks — and Scoop Dogg makes sure their backyards are just as enjoyable as the parks they visit.",
    neighborhoods: ['Dos Vientos', 'Borchard area', 'Old Conejo Road corridor', 'Camino Dos Rios', 'Wendy Drive area'],
    nearbySlug: ['thousand-oaks', 'camarillo', 'moorpark'],
    localContext: "Newbury Park's master-planned neighborhoods — especially Dos Vientos — feature well-maintained yards and HOA standards that make outdoor cleanliness important for everyone. Many families here have multiple dogs and active kids sharing the same backyard. We service Newbury Park on our Tuesday and Thursday Conejo Valley routes, grouping it efficiently with Thousand Oaks. New customers typically get their start date confirmed within 24 hours.",
    testimonial: {
      quote: "Our kids play in the backyard every day. Knowing it's clean every week gives me real peace of mind.",
      name: "Jessica A.",
      city: "Newbury Park",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Newbury Park?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing confirmed based on yard size and dogs.' },
      { q: 'What days do you service Newbury Park?', a: 'We service Newbury Park on Tuesdays and Thursdays as part of our Conejo Valley routes. Your specific day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes and we take care of everything, securing the gate when we leave.' },
      { q: 'Do you service Dos Vientos in Newbury Park?', a: 'Yes — Dos Vientos is one of our regular service areas. Many families in the community are on our weekly plan.' },
      { q: 'How do I get started in Newbury Park?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
  {
    name: 'Moorpark',
    slug: 'moorpark',
    tier: 2,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Moorpark, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Moorpark, CA. Serving Moorpark College area, Country Club Estates, and all neighborhoods.',
    intro: "Moorpark is a growing community known for Moorpark College, its friendly small-town feel, and well-kept residential neighborhoods like Country Club Estates. As more families settle in Moorpark and bring their dogs, keeping yards clean has become more important than ever. Scoop Dogg is proud to serve this community with reliable weekly and on-demand service.",
    neighborhoods: ['Country Club Estates', 'Moorpark College area', 'Campus Park', 'Mountain Meadows', 'High Street area'],
    nearbySlug: ['camarillo', 'thousand-oaks', 'simi-valley', 'newbury-park'],
    localContext: "Moorpark is growing fast, and newer developments like Mountain Meadows bring larger lots and more multi-dog households to the area. Many homes here also have artificial turf installed as part of drought-conscious landscaping — which looks great but needs enzyme treatment to stay odor-free. We service Moorpark on our Wednesday and Friday routes, and new customers are typically confirmed and scheduled within 24 hours of booking.",
    testimonial: {
      quote: "I was skeptical but after the first visit I was sold. The yard looked brand new.",
      name: "Brian H.",
      city: "Moorpark",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Moorpark?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Final pricing based on yard size and dogs.' },
      { q: 'What days do you service Moorpark?', a: 'We run Moorpark routes on Wednesdays and Fridays. Your day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access in your booking notes. We handle everything and always secure the gate.' },
      { q: 'Do you service new developments in Moorpark?', a: 'Yes — we service all established and newer neighborhoods in Moorpark, including recently built communities and master-planned areas.' },
      { q: 'How do I get started in Moorpark?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a couple days.' },
    ],
  },
  {
    name: 'Simi Valley',
    slug: 'simi-valley',
    tier: 1,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Simi Valley, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Simi Valley, CA. Serving Rancho Simi, Madera Road area, Reagan Library area, and all neighborhoods.',
    intro: "Simi Valley is a proud, family-oriented city with wide-open spaces, the historic Reagan Presidential Library, and thriving residential neighborhoods like Rancho Simi along Madera Road. With a large dog-owning population and spacious backyards, Simi Valley homeowners count on Scoop Dogg to keep things clean and odor-free all year long.",
    neighborhoods: ['Rancho Simi', 'Wood Ranch', 'Bridle Path', 'Big Sky', 'Madera Road corridor', 'Country Club area'],
    nearbySlug: ['moorpark', 'thousand-oaks', 'newbury-park'],
    localContext: "Simi Valley is one of the warmest areas in our service territory — summer heat accelerates odor and bacteria growth in yards with artificial turf, which is common in many newer Simi builds. Wood Ranch and Big Sky properties tend to have larger lots and multiple dogs, which is why many families here opt for weekly service. We run Simi Valley routes on Mondays and Thursdays, and new customers typically receive a confirmation within 24 hours of booking.",
    testimonial: {
      quote: "Honest, reliable, and my dog approves. My yard smells like nothing — and that's exactly the point.",
      name: "Tom G.",
      city: "Simi Valley",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Simi Valley?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing confirmed based on yard size and dog count.' },
      { q: 'What days do you service Simi Valley?', a: 'We run Simi Valley routes on Mondays and Thursdays. Your day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate codes or access info in your booking notes and we handle everything, securing the gate behind us.' },
      { q: 'Do you cover Wood Ranch and the east side of Simi Valley?', a: 'Yes — we service all of Simi Valley including Wood Ranch, Big Sky, Bridle Path, Rancho Simi, and the Madera Road corridor.' },
      { q: 'How do I get started in Simi Valley?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
  {
    name: 'Santa Barbara',
    slug: 'santa-barbara',
    tier: 1,
    region: 'nearby',
    metaTitle: 'Dog Poop Cleaning in Santa Barbara, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Santa Barbara, CA. Serving State Street, The Mesa, Goleta area, and all neighborhoods.',
    intro: "Santa Barbara is one of California's most iconic destinations, with stunning Spanish colonial architecture along State Street, the laid-back energy of The Mesa neighborhood, and proximity to the beaches and trails that dog owners in the area cherish. Scoop Dogg brings professional, no-hassle pet waste removal to Santa Barbara so you and your pup can fully enjoy everything this beautiful city has to offer.",
    neighborhoods: ['The Mesa', 'State Street area', 'Eastside', 'Westside', 'Mission Canyon', 'Hope Ranch adjacent', 'Goleta'],
    nearbySlug: ['carpinteria', 'ventura'],
    localContext: "Santa Barbara's mild year-round climate is perfect for outdoor living — which means dogs spend more time outside, and yards need more consistent attention. The Mesa and Mission Canyon neighborhoods feature older properties with established landscaping, while Goleta has a mix of newer homes with turf. We run Santa Barbara on a Tuesday and Friday coastal route, and because it's a longer drive from our home base, we group clients efficiently to keep pricing competitive. Expect confirmation within 24 hours of booking.",
    testimonial: {
      quote: "Worth every penny. I have a small yard but two big dogs. Scoop Dogg keeps it immaculate.",
      name: "Sarah M.",
      city: "Santa Barbara",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Santa Barbara?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing confirmed after booking based on yard and dogs.' },
      { q: 'What days do you service Santa Barbara?', a: 'We run the Santa Barbara coastal route on Tuesdays and Fridays. Your day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Provide gate access in your booking notes and we handle everything, securing the gate behind us.' },
      { q: 'Do you service the Mesa and Goleta neighborhoods?', a: 'Yes — The Mesa is one of our Santa Barbara service areas. We also cover Goleta, Eastside, Westside, Mission Canyon, and more.' },
      { q: 'How do I get started in Santa Barbara?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and will let you know your route day.' },
    ],
  },
  {
    name: 'Westlake Village',
    slug: 'westlake-village',
    tier: 2,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Westlake Village, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Westlake Village, CA. Serving North Ranch, Westlake Lake, and all neighborhoods. Weekly & one-time service.',
    intro: "Westlake Village is one of Southern California's most picturesque master-planned communities, with beautiful lakeside living, upscale neighborhoods in North Ranch, and tree-lined streets that dog owners love to walk. Scoop Dogg keeps yards in Westlake Village spotless so you can fully enjoy the outdoor lifestyle this stunning community offers.",
    neighborhoods: ['North Ranch', 'Westlake Lake area', 'Lakeview Canyon', 'Bridgeport', 'Westlake Island'],
    nearbySlug: ['thousand-oaks', 'newbury-park', 'moorpark'],
    localContext: "Westlake Village's manicured neighborhoods and HOA-managed communities set high expectations for outdoor appearance — and that includes backyards. Many properties near the lake and in North Ranch feature larger lots with mature landscaping that requires careful navigation. We service Westlake on our Tuesday and Thursday Conejo Valley routes, grouping it efficiently with nearby Thousand Oaks and Newbury Park. New customers are confirmed within 24 hours of booking.",
    testimonial: {
      quote: "I love that my yard looks as good as the neighborhood. Scoop Dogg makes it effortless.",
      name: "Jennifer L.",
      city: "Westlake Village",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Westlake Village?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing confirmed based on yard size and dogs.' },
      { q: 'What days do you service Westlake Village?', a: 'We service Westlake Village on Tuesdays and Thursdays as part of our Conejo Valley routes. Your specific day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes and we take care of everything, securing the gate when we leave.' },
      { q: 'Do you service gated communities in Westlake Village?', a: 'Yes — we work with gated and HOA communities regularly. Just provide gate codes or access info in the notes section when booking.' },
      { q: 'How do I get started in Westlake Village?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
  {
    name: 'Malibu',
    slug: 'malibu',
    tier: 3,
    region: 'nearby',
    metaTitle: 'Dog Poop Cleaning in Malibu, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Malibu, CA. Serving Point Dume, Malibu Colony, Carbon Beach, and all neighborhoods. Weekly & one-time service.',
    intro: "Malibu is iconic — 21 miles of Pacific coastline, world-class surf breaks, and some of the most beautiful residential properties in California. Dog owners here enjoy a lifestyle that blends beach living with canyon serenity, and Scoop Dogg keeps their yards as pristine as their surroundings. Whether you're near the shore or tucked into the hills, we've got your property covered.",
    neighborhoods: ['Point Dume', 'Malibu Colony', 'Carbon Beach', 'Zuma Beach area', 'Malibu Canyon', 'Serra Retreat', 'Big Rock'],
    nearbySlug: ['westlake-village', 'thousand-oaks'],
    localContext: "Malibu's coastal environment means salt air, marine layer moisture, and sandy or rocky terrain that presents unique challenges for yard maintenance. Canyon properties can have steep, uneven ground while beachside lots deal with moisture-related odor buildup year-round. We service Malibu on a dedicated coastal route and group clients geographically to keep service efficient. Because properties here can be spread out, we recommend booking in advance to secure your preferred day.",
    testimonial: {
      quote: "Not easy to find reliable help out here, but Scoop Dogg shows up every week without fail.",
      name: "Chris D.",
      city: "Malibu",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Malibu?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Final pricing confirmed based on your yard and dogs.' },
      { q: 'What days do you service Malibu?', a: 'We run a dedicated Malibu route and confirm your service day when you book. Days vary based on your specific location along the coast.' },
      { q: 'Do I need to be home when you come?', a: 'No. Provide gate access or entry instructions in your booking notes and we handle everything, securing the gate when we leave.' },
      { q: 'Do you service canyon properties and beach homes in Malibu?', a: 'Yes — we service all types of Malibu properties including canyon homes with steep terrain, gated estates, and beachside lots.' },
      { q: 'How do I get started in Malibu?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and will let you know your route day.' },
    ],
  },
  {
    name: 'Fillmore',
    slug: 'fillmore',
    tier: 3,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Fillmore, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Fillmore, CA. Serving Downtown Fillmore and surrounding residential areas. Weekly & one-time service.',
    intro: "Fillmore is a proud agricultural community in the heart of Ventura County's Santa Clara River Valley, known for its small-town character, working ranches, and the iconic Fillmore & Western Railway. Dog owners here tend to have larger properties, multiple pets, and busy schedules — which is exactly why Scoop Dogg's reliable, no-fuss service is such a good fit for Fillmore families.",
    neighborhoods: ['Downtown Fillmore', 'Sespe area', 'Mountain View area', 'Old Telegraph Road corridor', 'Bardsdale'],
    nearbySlug: ['santa-paula', 'ojai', 'ventura'],
    localContext: "Fillmore's warm inland climate and agricultural surroundings mean yards dry out fast in summer, but spring rains can create muddy conditions that complicate cleanup. Many properties here are larger than typical suburban lots, with fruit trees, irrigation channels, or working land that requires careful navigation. We service Fillmore on our Monday and Thursday inland routes alongside Santa Paula and Ojai, and new customers are typically confirmed within 24 hours of booking.",
    testimonial: {
      quote: "Finally a service that comes all the way out here. Dependable every single week.",
      name: "Maria G.",
      city: "Fillmore",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Fillmore?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. We confirm pricing based on your yard and dog count.' },
      { q: 'What days do you service Fillmore?', a: 'Fillmore is on our Monday and Thursday inland route alongside Santa Paula. Your day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes. We handle everything and always secure the gate when we leave.' },
      { q: 'Do you service larger rural properties in Fillmore?', a: 'Yes — we are experienced with larger lots, agricultural properties, and rural terrain. Just let us know about your property when you book.' },
      { q: 'How do I get started in Fillmore?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
  {
    name: 'Agoura Hills',
    slug: 'agoura-hills',
    tier: 2,
    region: 'ventura-county',
    metaTitle: 'Dog Poop Cleaning in Agoura Hills, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Agoura Hills, CA. Serving Morrison Ranch, Lake Lindero, and all neighborhoods. Weekly & one-time service.',
    intro: "Agoura Hills is a scenic community nestled in the eastern Santa Monica Mountains, known for its equestrian heritage, the upscale Morrison Ranch neighborhood, and beautiful views throughout the Lake Lindero area. Dog owners here appreciate the perfect balance of suburban convenience and natural beauty — and Scoop Dogg keeps their yards spotless so they can fully enjoy both.",
    neighborhoods: ['Morrison Ranch', 'Lake Lindero', 'Old Agoura', 'Agoura Hills South', 'Freedom Park area'],
    nearbySlug: ['westlake-village', 'thousand-oaks', 'malibu'],
    localContext: "Agoura Hills combines hillside properties with master-planned communities, creating diverse yard maintenance needs. Morrison Ranch and Lake Lindero feature larger lots with manicured landscaping, while Old Agoura offers a more rural feel with horse properties and bigger yards. Many homes here have artificial turf as part of drought-conscious landscaping, which requires regular enzyme deodorizing. We service Agoura Hills on our Tuesday and Thursday Conejo Valley routes alongside Westlake Village and Thousand Oaks, with new customers confirmed within 24 hours of booking.",
    testimonial: {
      quote: "We moved here for the trails and open space. Scoop Dogg makes sure our yard matches the beauty of the neighborhood.",
      name: "Michelle R.",
      city: "Agoura Hills",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Agoura Hills?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Pricing confirmed based on yard size and number of dogs.' },
      { q: 'What days do you service Agoura Hills?', a: 'We service Agoura Hills on Tuesdays and Thursdays as part of our Conejo Valley routes. Your specific day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes and we take care of everything, securing the gate when we leave.' },
      { q: 'Do you service Morrison Ranch and Lake Lindero?', a: 'Yes — both Morrison Ranch and Lake Lindero are regular service areas for us. Many families in these neighborhoods are on our weekly plan.' },
      { q: 'How do I get started in Agoura Hills?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
  {
    name: 'Carpinteria',
    slug: 'carpinteria',
    tier: 1,
    region: 'nearby',
    metaTitle: 'Dog Poop Cleaning in Carpinteria, CA | Scoop Dogg',
    metaDescription: 'Professional poop scooping in Carpinteria, CA. Serving Carpinteria State Beach area and all neighborhoods.',
    intro: "Carpinteria is a beloved beach town just south of Santa Barbara, famous for Carpinteria State Beach, the avocado festival, and its warm, welcoming community spirit. Dog owners here love the outdoor lifestyle — and Scoop Dogg makes sure their home bases stay just as clean as the beautiful beaches they visit. We're proud to serve Carpinteria's tight-knit neighborhoods.",
    neighborhoods: ['Downtown Carpinteria', 'Carpinteria State Beach area', 'Rincon Point neighborhood', 'El Carro', 'Summerland adjacent'],
    nearbySlug: ['santa-barbara', 'ventura'],
    localContext: "Carpinteria's coastal microclimate keeps yards moist year-round, and the sandy soil near the beach can make cleanup more challenging than a typical inland property. Many homeowners here are part-time residents or weekend visitors who need occasional deep cleans rather than weekly service — though plenty of full-time locals are on our regular route. We service Carpinteria on our Tuesday coastal run alongside Santa Barbara, and confirm new customers within 24 hours of booking.",
    testimonial: {
      quote: "We're a beach town family — the dogs are always in the yard. Scoop Dogg keeps it usable.",
      name: "Lori C.",
      city: "Carpinteria",
    },
    faqs: [
      { q: 'How much does pooper scooper service cost in Carpinteria?', a: 'Weekly service is $15/week for 1 dog, $20/week for 2 dogs, $23/week for 3 dogs, and $25/week for 4 or more dogs. A Turf Deep Clean is a flat $99. Turf Rescue deodorizing starts at $20. Final pricing depends on yard size and dogs.' },
      { q: 'What days do you service Carpinteria?', a: 'Carpinteria is on our Tuesday coastal route alongside Santa Barbara. Your specific day is confirmed when you book.' },
      { q: 'Do I need to be home when you come?', a: 'No. Leave gate access details in your booking notes and we handle everything, securing the gate when we leave.' },
      { q: 'Can sandy yards or beach-adjacent properties be serviced?', a: 'Yes — our team is experienced with all yard types including sandy soil and beach-adjacent properties common on the Carpinteria coastline.' },
      { q: 'How do I get started in Carpinteria?', a: 'Book online using the form on this page or call (805) 869-8070. We confirm same day and can usually start within a few days.' },
    ],
  },
];

export const CITY_MAP: Record<string, CityData> = Object.fromEntries(
  CITIES.map((c) => [c.slug, c])
);

export const CITY_NAMES = CITIES.map((c) => c.name);
export const CITY_SLUGS = CITIES.map((c) => c.slug);
