export interface ServiceData {
  slug: string;
  name: string;
  shortName: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  whatIncludes: string[];
  whoItsFor: string;
  pricing: { label: string; price: string }[];
  pricingNote: string;
  relatedSlugs: string[];
  faqs: { q: string; a: string }[];
  bookingId: string;
}

export const SERVICES: ServiceData[] = [
  {
    slug: 'weekly-pooper-scooper-service',
    name: 'Weekly Pooper Scooper Service',
    shortName: 'Weekly Scooping',
    metaTitle: 'Weekly Pooper Scooper Service in Ventura County | Scoop Dogg',
    metaDescription: 'Scheduled weekly dog poop cleaning starting at $15/visit. We scoop, bag, and haul off all waste. Cancel anytime. Serving 15 cities in Ventura County.',
    h1: 'Weekly Pooper Scooper Service in Ventura County',
    intro: 'Our most popular service. We show up on the same day every week, walk your entire yard, scoop every pile, bag it, and haul it off your property. You never need to be home. Skip a week, pause for vacation, or cancel anytime. Most customers start at $15/week for one dog and never look back.',
    whatIncludes: [
      'Full property walk — every corner, behind planters, under decks',
      'All waste scooped, double-bagged, and removed from your property',
      'Gate secured after every visit',
      'Same-day text confirmation when complete',
      'Consistent weekly schedule (same day every week)',
    ],
    whoItsFor: 'Homeowners who want a clean yard without thinking about it. Especially popular with busy families, multi-dog households, seniors, and anyone who has tried (and failed) to keep up with scooping on their own.',
    pricing: [
      { label: '1 dog', price: '$15/week' },
      { label: '2 dogs', price: '$20/week' },
      { label: '3 dogs', price: '$23/week' },
      { label: '4+ dogs', price: '$25/week' },
    ],
    pricingNote: 'No sign-up fees. Cancel or pause anytime.',
    relatedSlugs: ['artificial-turf-deodorizing', 'one-time-dog-poop-cleanup', 'yard-deep-clean'],
    faqs: [
      { q: 'Do I need to be home during service?', a: 'No. Just make sure we have gate access. Leave codes or instructions when you book and we handle everything, then secure the gate behind us.' },
      { q: 'What happens to the waste?', a: 'We double-bag all waste and remove it from your property entirely. It does not go in your trash cans.' },
      { q: 'Can I skip a week or pause service?', a: 'Absolutely. Just let us know in advance. No fees for skipping or pausing — we resume whenever you are ready.' },
      { q: 'How quickly can I start?', a: 'Most new customers are confirmed within 24 hours and start within a few days, depending on route availability in your area.' },
      { q: 'Is there a contract or commitment?', a: 'Never. We earn your business every visit. Cancel anytime with no questions asked.' },
    ],
    bookingId: 'weekly',
  },
  {
    slug: 'one-time-dog-poop-cleanup',
    name: 'One-Time Dog Poop Cleanup',
    shortName: 'One-Time Cleanup',
    metaTitle: 'One-Time Dog Poop Cleanup in Ventura County | Scoop Dogg',
    metaDescription: 'Full yard poop cleanup for overgrown or neglected yards. Perfect for moving, hosting, or getting back to zero. Starting at $99. Serving Ventura County.',
    h1: 'One-Time Dog Poop Cleanup in Ventura County',
    intro: 'Sometimes yards get away from you. Maybe you just moved in, maybe it has been a few months, or maybe you are hosting this weekend and need a reset. Our one-time cleanup tackles the full backlog — we walk the entire property, scoop every pile no matter how old, and haul it all away. One visit, clean slate.',
    whatIncludes: [
      'Complete property walk and full waste removal',
      'All waste scooped regardless of age or accumulation',
      'Double-bagged and hauled off your property',
      'Gate secured after service',
      'Optional transition to weekly service at standard pricing',
    ],
    whoItsFor: 'New homeowners inheriting a messy yard, landlords preparing a rental, anyone hosting an event, or dog owners who have fallen behind and want a fresh start before committing to weekly.',
    pricing: [
      { label: 'Standard yard (up to 2 weeks buildup)', price: '$99' },
      { label: 'Heavy buildup (3-6 weeks)', price: '$149' },
      { label: 'Severe (6+ weeks or multiple dogs)', price: 'Custom quote' },
    ],
    pricingNote: 'Final pricing confirmed after booking based on yard size and buildup level.',
    relatedSlugs: ['weekly-pooper-scooper-service', 'yard-deep-clean', 'artificial-turf-deodorizing'],
    faqs: [
      { q: 'How long does a one-time cleanup take?', a: 'Most yards take 30-60 minutes depending on size and accumulation. Heavily built-up yards may take longer.' },
      { q: 'Can I switch to weekly service after?', a: 'Yes — many customers start with a one-time cleanup and then transition to weekly. No additional setup fee.' },
      { q: 'Do you handle really bad yards?', a: 'Yes. We have seen it all — months of buildup, multiple large dogs, overgrown areas. We will get it done.' },
      { q: 'What if I am not sure how bad it is?', a: 'Book online and describe what you are dealing with. We will give you an honest quote before we start. No surprises.' },
      { q: 'Is the waste removed from my property?', a: 'Yes. Everything is double-bagged and hauled away. Nothing goes in your bins.' },
    ],
    bookingId: 'one-time',
  },
  {
    slug: 'artificial-turf-deodorizing',
    name: 'Artificial Turf Deodorizing',
    shortName: 'Turf Deodorizing',
    metaTitle: 'Artificial Turf Deodorizing in Ventura County | Scoop Dogg',
    metaDescription: 'Enzyme-based turf deodorizing that eliminates pet urine odor from artificial grass, gravel, and concrete. Pet-safe, 100% natural. Starting at $20. Ventura County.',
    h1: 'Artificial Turf Deodorizing in Ventura County',
    intro: 'Artificial turf looks great — until your dogs use it as a bathroom. Urine seeps into the infill and backing, creating persistent odor that water alone cannot fix. Our enzyme-based deodorizing treatment breaks down the bacteria causing the smell at a molecular level. It works on turf, gravel, concrete, patios, and natural grass. 100% pet-safe — dogs can use the yard immediately after application.',
    whatIncludes: [
      'Surface debris removal and rinse',
      'Professional enzyme deodorizer application',
      'Bacteria and odor elimination at the source',
      'Works on artificial turf, gravel, concrete, and natural grass',
      'Safe for pets immediately after treatment',
    ],
    whoItsFor: 'Homeowners with artificial turf or hardscape areas where dog urine has created persistent odor. Especially common in newer Ventura County homes where turf replaced water-hungry lawns.',
    pricing: [
      { label: 'Small area (under 200 sq ft)', price: '$20' },
      { label: 'Medium area (200-500 sq ft)', price: '$35' },
      { label: 'Large area (500+ sq ft)', price: '$50+' },
    ],
    pricingNote: 'Add to weekly service or book standalone. Often paired with a Turf Deep Clean for maximum results.',
    relatedSlugs: ['yard-deep-clean', 'weekly-pooper-scooper-service', 'one-time-dog-poop-cleanup'],
    faqs: [
      { q: 'Is the deodorizer safe for dogs?', a: 'Yes, 100%. The enzymes are natural and non-toxic. Your dogs can use the yard immediately after application.' },
      { q: 'How long does the treatment last?', a: 'Results are immediate and typically last 2-4 weeks depending on how frequently your dogs use the area. Most clients add it to their weekly service.' },
      { q: 'Does it work on real grass too?', a: 'Yes. The enzyme treatment works on artificial turf, gravel, concrete, pavers, and natural grass.' },
      { q: 'Can I combine this with weekly scooping?', a: 'Absolutely. Many of our weekly clients add deodorizing as a regular add-on, especially during warmer months when odor is worse.' },
      { q: 'Will it remove all the smell?', a: 'In most cases, yes. For heavily saturated turf that has never been treated, we may recommend a Turf Deep Clean first to reset the surface before ongoing enzyme maintenance.' },
    ],
    bookingId: 'turf',
  },
  {
    slug: 'yard-deep-clean',
    name: 'Yard Deep Clean',
    shortName: 'Deep Clean',
    metaTitle: 'Yard & Turf Deep Clean in Ventura County | Scoop Dogg',
    metaDescription: 'Full turf and yard deep clean: brush, vacuum, pressure wash, and heavy deodorizer. Ideal for seasonal resets and new homeowners. Starting at $99. Ventura County.',
    h1: 'Yard & Turf Deep Clean in Ventura County',
    intro: 'A full reset for your outdoor surface. We deep-brush the turf to loosen embedded debris, vacuum the infill, pressure wash the surface, and apply a heavy-duty deodorizer and sanitizer. This is not a quick spray — it is a thorough restoration that leaves your turf looking and smelling like the day it was installed. Recommended 2-3 times per year or when you are inheriting a yard from a previous owner.',
    whatIncludes: [
      'Deep brush to loosen embedded waste and debris',
      'Infill vacuum and debris extraction',
      'Pressure wash of entire surface',
      'Heavy-duty enzyme deodorizer and sanitizer application',
      'Final rinse and inspection',
    ],
    whoItsFor: 'New homeowners inheriting turf from previous owners, anyone doing a seasonal yard reset, or properties where regular enzyme treatments alone are not solving persistent odor.',
    pricing: [
      { label: 'Standard turf area (under 500 sq ft)', price: '$99' },
      { label: 'Large turf area (500-1000 sq ft)', price: '$149' },
      { label: 'Extra large (1000+ sq ft)', price: 'Custom quote' },
    ],
    pricingNote: 'Often combined with ongoing weekly service + enzyme deodorizing for long-term results.',
    relatedSlugs: ['artificial-turf-deodorizing', 'weekly-pooper-scooper-service', 'one-time-dog-poop-cleanup'],
    faqs: [
      { q: 'How often should I get a deep clean?', a: 'We recommend 2-3 times per year for most properties. Homes with multiple dogs or heavy use may benefit from quarterly service.' },
      { q: 'Is this the same as regular deodorizing?', a: 'No. A deep clean includes physical cleaning (brush, vacuum, pressure wash) plus deodorizing. Regular deodorizing is enzyme treatment only.' },
      { q: 'How long does a deep clean take?', a: 'Most standard properties take 1-2 hours. Larger or heavily soiled areas may take longer.' },
      { q: 'Can I walk on the turf right after?', a: 'We recommend waiting 1-2 hours for the surface to dry after pressure washing. The deodorizer is pet-safe immediately.' },
      { q: 'Do you also handle natural grass and yard debris?', a: 'Yes. While this service is designed for turf and hardscape, we can address natural grass areas and general yard debris as part of a custom quote.' },
    ],
    bookingId: 'yard-deep-clean',
  },
  {
    slug: 'weekly-turf-maintenance',
    name: 'Weekly Turf Maintenance',
    shortName: 'Turf Maintenance',
    metaTitle: 'Weekly Turf Maintenance Service in Ventura County | Scoop Dogg',
    metaDescription: 'Ongoing artificial turf sweeping and deodorizing in Ventura County. We use the SwipeSmith turf sweeper for leaf, debris, and pet hair removal plus enzyme treatment. Starting at $35/visit.',
    h1: 'Weekly Turf Maintenance in Ventura County',
    intro: 'After a deep clean, your turf needs regular upkeep to stay fresh. We come back weekly with the SwipeSmith artificial turf sweeper to pick up leaves, twigs, pet hair, and debris that collect between visits. Each visit includes an enzyme deodorizer application to keep odor at zero. This is the ongoing maintenance that keeps your turf looking and smelling like it did on installation day.',
    whatIncludes: [
      'SwipeSmith turf sweeper pass over entire surface',
      'Leaf, twig, and pet hair removal',
      'Enzyme deodorizer application',
      'Infill redistribution as needed',
      'Visual inspection for wear or drainage issues',
    ],
    whoItsFor: 'Homeowners with artificial turf who want consistent weekly care. Whether you have dogs using the turf or just want it looking pristine, this service keeps debris from building up and odor from taking hold.',
    pricing: [
      { label: 'Small area (under 300 sq ft)', price: '$35/visit' },
      { label: 'Medium area (300-600 sq ft)', price: '$50/visit' },
      { label: 'Large area (600+ sq ft)', price: 'Custom quote' },
    ],
    pricingNote: 'Best results when paired with a deep clean 2-3 times per year. First month half off when combined with weekly poop scooping.',
    relatedSlugs: ['yard-deep-clean', 'artificial-turf-deodorizing', 'weekly-pooper-scooper-service'],
    faqs: [
      { q: 'What is the SwipeSmith turf sweeper?', a: 'It is a specialized grooming mower designed for artificial turf. It brushes fibers upright, picks up embedded debris, and redistributes infill — all without damaging the turf surface.' },
      { q: 'Do I need a deep clean first?', a: 'We recommend starting with a deep clean if your turf has not been professionally cleaned before. After that, weekly maintenance keeps it in peak condition between deep cleans.' },
      { q: 'Is this just for pet owners?', a: 'No. Turf collects leaves, pollen, dust, and debris regardless of pets. Weekly maintenance benefits anyone with artificial turf who wants it looking its best.' },
      { q: 'How is this different from the enzyme deodorizing service?', a: 'Enzyme deodorizing is a standalone odor treatment. Weekly turf maintenance includes the sweeper pass, debris removal, AND enzyme treatment — it is a complete turf care visit.' },
    ],
    bookingId: 'turf',
  },
  {
    slug: 'weekly-yard-maintenance',
    name: 'Weekly Yard Maintenance',
    shortName: 'Yard Maintenance',
    metaTitle: 'Weekly Yard Maintenance & Landscaping in Ventura County | Scoop Dogg',
    metaDescription: 'Weekly yard maintenance in Ventura County — mowing, trimming, edging, and cleanup. Keep your property looking sharp every week. Custom quotes based on property size.',
    h1: 'Weekly Yard Maintenance in Ventura County',
    intro: 'Ongoing yard maintenance tailored to what your property actually needs. Mowing, edging, hedge trimming, leaf cleanup, or a combination — we keep things looking sharp between deep cleans so your outdoor space is always guest-ready. Same reliable team, same day every week.',
    whatIncludes: [
      'Lawn mowing and edging',
      'Hedge and shrub trimming',
      'Leaf and debris cleanup',
      'Walkway and patio sweeping',
      'Customizable service based on your property',
    ],
    whoItsFor: 'Homeowners who want a consistently clean and maintained yard without managing multiple contractors. Great as a follow-up to a yard deep clean or overgrowth reset.',
    pricing: [
      { label: 'Small yard (basic mow & edge)', price: 'From $40/visit' },
      { label: 'Medium yard (mow, edge, trim)', price: 'From $65/visit' },
      { label: 'Large or custom property', price: 'Custom quote' },
    ],
    pricingNote: 'Pricing based on property size and services needed. We provide a custom quote after seeing your property.',
    relatedSlugs: ['yard-deep-clean', 'weekly-pooper-scooper-service', 'pressure-washing'],
    faqs: [
      { q: 'What does weekly maintenance include?', a: 'It depends on your property. Most clients get mowing, edging, and basic trimming. We can add leaf cleanup, shrub shaping, and other tasks based on what you need.' },
      { q: 'Can I combine this with poop scooping?', a: 'Absolutely. Many clients pair weekly yard maintenance with weekly poop scooping — same visit, same team.' },
      { q: 'Do you do one-time landscaping jobs too?', a: 'Yes. Our Yard Deep Clean service handles one-time restoration and overgrowth. Weekly maintenance is for ongoing upkeep after the heavy lifting is done.' },
      { q: 'How do I get a quote?', a: 'Book through our form and describe your property. We will follow up same day with a custom quote based on yard size and the services you need.' },
    ],
    bookingId: 'yard-maintenance',
  },
  {
    slug: 'kitty-litter-exchange',
    name: 'Kitty Litter Exchange',
    shortName: 'Litter Exchange',
    metaTitle: 'Kitty Litter Exchange Service in Ventura County | Scoop Dogg',
    metaDescription: 'Fresh litter box service for cat owners in Ventura County. We remove used litter, refresh the box, and keep indoor pet areas cleaner. Book today.',
    h1: 'Kitty Litter Exchange in Ventura County',
    intro: 'Fresh litter box service for cat owners who want the dirty work handled. We remove used litter, refresh the box, and help keep indoor pet areas cleaner. No more putting it off, no more smell building up — just a clean box on a schedule that works for you.',
    whatIncludes: [
      'Used litter removed and bagged for disposal',
      'Box wiped down and refreshed with clean litter',
      'Surrounding area tidied if needed',
      'Flexible scheduling — weekly or as-needed',
      'Safe, odor-controlled handling',
    ],
    whoItsFor: 'Cat owners who want to stay on top of litter box hygiene without the hassle. Great for busy households, people with mobility limitations, multi-cat homes, and anyone who just hates doing it.',
    pricing: [
      { label: '1 litter box', price: '$15/visit' },
      { label: '2 litter boxes', price: '$22/visit' },
      { label: '3+ litter boxes', price: 'Custom quote' },
    ],
    pricingNote: 'Litter not included unless requested. Add-on to existing service or book standalone.',
    relatedSlugs: ['cat-tree-cleaning', 'weekly-pooper-scooper-service'],
    faqs: [
      { q: 'Do you bring the fresh litter?', a: 'We can use litter you already have on hand or supply it for an additional fee. Just let us know when you book.' },
      { q: 'Do I need to be home?', a: 'No. As long as we have safe indoor access, we can handle the exchange without you there.' },
      { q: 'How often should litter boxes be exchanged?', a: 'Most cat owners benefit from a full litter exchange once a week. High-use boxes or multi-cat homes may need more frequent attention.' },
    ],
    bookingId: 'kitty-litter',
  },
  {
    slug: 'dog-run-cleanups',
    name: 'Dog Run Cleanups',
    shortName: 'Dog Run Cleanup',
    metaTitle: 'Dog Run Cleanup Service in Ventura County | Scoop Dogg',
    metaDescription: 'Cleanup for side yards, gravel runs, turf strips, and fenced dog areas in Ventura County. Waste removal and odor control for high-use pet zones.',
    h1: 'Dog Run Cleanup in Ventura County',
    intro: 'Cleanup for side yards, gravel runs, artificial turf strips, fenced dog areas, and high-use potty zones where waste and odor build up fast. These spots get ignored because they are out of sight — but they are usually the worst-smelling part of the property. We get in there, scoop everything out, and leave it clean.',
    whatIncludes: [
      'Full waste removal from the run or enclosed area',
      'All surfaces checked — gravel, turf, concrete, dirt',
      'Double-bagged waste hauled off property',
      'Odor assessment and optional enzyme treatment',
      'Gate secured and area reset after service',
    ],
    whoItsFor: 'Homeowners with dedicated dog runs, side-yard potty areas, or any enclosed space where dogs spend time and waste accumulates. Especially common in homes with gravel or turf runs.',
    pricing: [
      { label: 'Small run (under 100 sq ft)', price: '$49' },
      { label: 'Medium run (100-300 sq ft)', price: '$79' },
      { label: 'Large or custom area', price: 'Custom quote' },
    ],
    pricingNote: 'Enzyme deodorizing available as an add-on. Pricing based on size and accumulation level.',
    relatedSlugs: ['weekly-pooper-scooper-service', 'artificial-turf-deodorizing', 'pressure-washing'],
    faqs: [
      { q: 'Is this different from your regular yard scooping?', a: 'Yes. Dog runs are tighter, more concentrated areas that need focused attention. We treat them as a separate service because the cleanup intensity is different from a standard yard walk.' },
      { q: 'Do you handle gravel runs?', a: 'Yes. Gravel and decomposed granite are some of the most common dog run surfaces we work in. Waste hides easily in gravel so we are thorough.' },
      { q: 'Can I add enzyme treatment to the same visit?', a: 'Absolutely. Most dog run cleanups benefit from an enzyme deodorizer application after waste removal, especially if the run is artificial turf or concrete.' },
    ],
    bookingId: 'dog-run',
  },
  {
    slug: 'cat-tree-cleaning',
    name: 'Cat Tree Cleaning',
    shortName: 'Cat Tree Cleaning',
    metaTitle: 'Cat Tree Cleaning Service in Ventura County | Scoop Dogg',
    metaDescription: 'Professional cat tree and pet furniture cleaning in Ventura County. We remove hair, odor, litter dust, and everyday pet mess from cat trees and scratching posts.',
    h1: 'Cat Tree Cleaning in Ventura County',
    intro: 'Cleaning for cat trees, scratching posts, and pet furniture that collects hair, odor, litter dust, and everyday pet mess. Cat trees get grimy fast and most people never get around to cleaning them. We handle it without you having to drag the thing outside yourself.',
    whatIncludes: [
      'Hair removal from all levels and platforms',
      'Wipe-down of all surfaces and posts',
      'Odor treatment with pet-safe cleaner',
      'Litter dust and debris removal',
      'Inspection for wear or damage (noted, not repaired)',
    ],
    whoItsFor: 'Cat owners whose trees have been overdue for a proper cleaning. Especially useful after a cat illness, when adding a new cat to the household, or for multi-cat homes where the tree sees constant use.',
    pricing: [
      { label: 'Small tree (1-2 levels)', price: '$25' },
      { label: 'Large tree (3+ levels)', price: '$45' },
      { label: 'Multiple trees', price: 'Custom quote' },
    ],
    pricingNote: 'Pricing based on size and condition. Cleaning products are pet-safe.',
    relatedSlugs: ['kitty-litter-exchange', 'weekly-pooper-scooper-service'],
    faqs: [
      { q: 'Do you disassemble the cat tree to clean it?', a: 'We clean it in place for most standard trees. For trees that need disassembly to reach all areas, we will let you know beforehand.' },
      { q: 'What cleaning products do you use?', a: 'Pet-safe, enzyme-based cleaners that neutralize odor without harsh chemicals. Nothing that would harm your cats after the clean.' },
      { q: 'How often should cat trees be professionally cleaned?', a: 'A few times a year is reasonable for most households. Multi-cat homes or cats recovering from illness may benefit from more frequent cleaning.' },
    ],
    bookingId: 'cat-tree',
  },
  {
    slug: 'pressure-washing',
    name: 'Pressure Washing',
    shortName: 'Pressure Washing',
    metaTitle: 'Pet Area Pressure Washing in Ventura County | Scoop Dogg',
    metaDescription: 'Pet area pressure washing for patios, hardscape, dog runs, and outdoor surfaces in Ventura County. We clean hard surfaces after solid pet waste has been removed.',
    h1: 'Pet Area Pressure Washing in Ventura County',
    intro: 'Pet-area pressure washing for patios, hardscape, dog runs, and outdoor surfaces after solid waste has been removed. Dried residue, staining, and ground-in odor on concrete and pavers does not come out with a garden hose. High-pressure washing restores the surface and removes what regular cleaning leaves behind. We always remove solid waste first and wash responsibly — nothing goes toward gutters or storm drains.',
    whatIncludes: [
      'Solid waste removed before any washing begins',
      'High-pressure wash of concrete, pavers, tile, and hardscape',
      'Responsible water direction — away from gutters and storm drains',
      'Post-wash enzyme deodorizer application (optional)',
      'Surface inspection and rinse',
    ],
    whoItsFor: 'Homeowners with concrete patios, pavers, or hardscape in pet-use areas that have developed staining or persistent odor. Often combined with a dog run cleanup or yard deep clean.',
    pricing: [
      { label: 'Small patio or run (under 200 sq ft)', price: '$59' },
      { label: 'Medium area (200-500 sq ft)', price: '$99' },
      { label: 'Large area (500+ sq ft)', price: 'Custom quote' },
    ],
    pricingNote: 'Solid waste removal is included before washing. Enzyme deodorizing available as an add-on.',
    relatedSlugs: ['dog-run-cleanups', 'yard-deep-clean', 'artificial-turf-deodorizing'],
    faqs: [
      { q: 'Do you remove the pet waste before washing?', a: 'Yes, always. Solid waste is scooped and removed before any pressure washing begins. We never wash pet waste toward gutters, drains, or neighboring properties.' },
      { q: 'What surfaces can you pressure wash?', a: 'Concrete, pavers, brick, tile, and most hardscape. We do not pressure wash artificial turf — turf gets the enzyme deep clean treatment instead.' },
      { q: 'Can I add pressure washing to my regular cleanup visit?', a: 'Yes. Pressure washing is commonly added on to dog run cleanups, one-time yard cleanups, or yard deep cleans. Just mention it when you book.' },
    ],
    bookingId: 'pressure-washing',
  },
  {
    slug: 'kitty-litter-robot-cleaning',
    name: 'Kitty Litter Robot Cleaning',
    shortName: 'Litter Robot Cleaning',
    metaTitle: 'Kitty Litter Robot Cleaning Service in Ventura County | Scoop Dogg',
    metaDescription: 'Professional Litter-Robot cleaning service in Ventura County. We deep clean automatic self-cleaning litter boxes, remove buildup, eliminate odors, and keep your smart litter box working perfectly.',
    h1: 'Kitty Litter Robot Cleaning in Ventura County',
    intro: 'The Litter-Robot is an incredible invention — an automatic, self-cleaning litter box that uses a rotating globe and sensors to separate waste from clean litter after your cat leaves. But even the smartest litter box needs regular deep cleaning. Waste residue builds up in the globe, the waste drawer gets grimy, and odor can linger even when the unit is "clean." We handle the full teardown, deep clean, and reassembly so your Litter-Robot stays fresh and functional.',
    whatIncludes: [
      'Full globe interior wipe-down and scrub',
      'Waste drawer cleaned and deodorized',
      'Carbon filter replacement or refresh',
      'Exterior housing wiped and sanitized',
      'Sensor areas cleaned for optimal performance',
      'Reassembly and function check',
    ],
    whoItsFor: 'Cat owners with Litter-Robot or similar automatic self-cleaning litter boxes who want the device properly maintained without the hassle of taking it apart themselves. Great for multi-cat households where the unit sees heavy use, or anyone who wants to extend the life of their investment.',
    pricing: [
      { label: '1 Litter-Robot', price: '$45' },
      { label: '2 Litter-Robots', price: '$75' },
      { label: '3+ Litter-Robots', price: 'Custom quote' },
    ],
    pricingNote: 'Includes carbon filter refresh. Compatible with Litter-Robot 3, 4, and similar automatic units.',
    relatedSlugs: ['kitty-litter-exchange', 'cat-tree-cleaning'],
    faqs: [
      { q: 'What is a Litter-Robot?', a: 'The Litter-Robot is an automatic, self-cleaning litter box that uses a rotating globe and weight/laser sensors to separate waste clumps from clean litter after your cat leaves. Waste drops into a drawer below, eliminating the need for daily manual scooping.' },
      { q: 'Why does my Litter-Robot need cleaning?', a: 'Even though it self-cleans, residue builds up inside the globe and waste drawer over time. This can cause odor, affect the sensors, and reduce the unit\'s effectiveness. A deep clean restores performance and eliminates smells.' },
      { q: 'Do I need to be home for the service?', a: 'No, as long as we have safe indoor access. We will unplug the unit, perform the full cleaning, and have it back up and running when we are done.' },
      { q: 'How often should I get my Litter-Robot cleaned?', a: 'We recommend a deep clean every 2-3 months for single-cat homes, or monthly for multi-cat households. Heavy use and certain litter types may require more frequent attention.' },
      { q: 'What litter types work best with Litter-Robots?', a: 'Traditional clay-based clumping litter and select natural clumping litters work best. We can advise on litter choices during your service visit.' },
    ],
    bookingId: 'litter-robot',
  },
];

export const SERVICE_MAP: Record<string, ServiceData> = Object.fromEntries(
  SERVICES.map((s) => [s.slug, s])
);

export const SERVICE_SLUGS = SERVICES.map((s) => s.slug);
