#!/usr/bin/env python3
"""Generate migrations/002_leads.sql from the verified leads.json backup.

    python3 scripts/build-leads-migration.py <path-to-leads.json>

The 24 leads are the only irreplaceable data in the old database. leads.json was
verified field-by-field against the live database on 2026-09-10 by
output/backups/scoopdogg-2026-09-09/verify-leads.py.

Generating the SQL rather than hand-writing it means the migration can be rebuilt
from the source of truth and diffed, and that the row count in the file is a fact
rather than a claim.
"""
import json, sys
from pathlib import Path

# old column -> new column. service_type was renamed; everything else keeps its name.
RENAME = {"service_type": "service_slug"}
COLS = ["id","name","phone","email","address","city","service_slug","yard_size",
        "num_dogs","frequency","notes","source_page","status","created_at","updated_at"]

def lit(v):
    if v is None or v == "":
        return "NULL" if v is None else "''"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"

def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1
               else "../../output/backups/scoopdogg-2026-09-09/leads.json")
    rows = json.loads(src.read_text())

    out = [
        "-- Scoop Dogg - migrate the leads, and only the leads.",
        "--",
        "-- GENERATED by scripts/build-leads-migration.py from the backup JSON that was",
        "-- verified field-by-field against the live database on 2026-09-10. Do not hand-edit;",
        "-- regenerate. Nothing else from the old database is carried over: not the schema,",
        "-- not the RLS policies, not the keepalive table.",
        "--",
        f"-- {len(rows)} rows. Original ids preserved, so nothing a customer ever referenced changes.",
        "",
        "begin;",
        "",
    ]
    for r in rows:
        rec = {RENAME.get(k, k): v for k, v in r.items()}
        # yard_size and num_dogs are nullable now: '' is not a size and 0 dogs is a real answer
        if rec.get("yard_size") == "":
            rec["yard_size"] = None
        vals = ", ".join(lit(rec.get(c)) for c in COLS)
        out.append(f"insert into leads ({', '.join(COLS)}) values ({vals});")

    out += [
        "",
        f"-- The migration is wrong unless exactly {len(rows)} rows landed.",
        "do $$",
        "declare n integer;",
        "begin",
        "  select count(*) into n from leads;",
        f"  if n <> {len(rows)} then",
        f"    raise exception 'expected {len(rows)} leads after migration, found %', n;",
        "  end if;",
        "end $$;",
        "",
        "commit;",
        "",
    ]
    dest = Path(__file__).resolve().parent.parent / "migrations" / "002_leads.sql"
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({len(rows)} leads)")

if __name__ == "__main__":
    main()
